import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<ClerkProvider>
			<html lang='en'>
				<body className={inter.className}>
					<div className='container mx-auto px-12'>
						<nav
							style={{ display: 'flex', justifyContent: 'space-between' }}
							className='mb-4 mt-2'
						>
							<Link href='/'>
								<h2 className='font-bold m-3'>MySnippets</h2>
							</Link>
							<div className=' flex justify-center items-center bg-blue-200 p-2 rounded'>
								<Link href='/snippets/new'>Add New</Link>
								<Link href='/sign-in'>Sign-in</Link>
							</div>
						</nav>
						{children}
					</div>
				</body>
			</html>
		</ClerkProvider>
	)
}
